config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts
  resources :users, except: [:new]
  root 'pages#home'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :tags, except: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article_tag.rb
class ArticleTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :article_tags
  has_many :tags, through: :article_tags
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :body, presence: true, length: {minimum: 10, maximum: 1000}
  validates :user_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :article_tags
  has_many :posts, through: :article_tags
  validates :name, presence: true, length: {minimum: 3, maximum: 20}
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :username, presence: true, uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }
  validates :email, presence: true, uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_login
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to posts_path if logged_in?
  end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:edit, :update, :show, :destroy]
  before_action :redirect_unless_authorized, only: [:edit, :update, :destroy]

  def index
    @posts = Post.paginate(page: params[:page], per_page: 5)
  end

  def new
    @post = Post.new
  end

  def create
    # render plain: params[:post].inspect
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to post_path(@post)
      flash[:notice] = "Post was successfully created!"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Post was successfully updated!"
      redirect_to post_path(@post)
    else
      render :edit
    end
   end

   def destroy
     @post.destroy
     flash[:notice] = "Post was successfully deleted!"
     redirect_to posts_path
   end

private
  def post_params
      params.require(:post).permit(:title, :body, tag_ids: [])
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def redirect_unless_authorized
    unless current_user == @post.user || current_user.admin?
      flash[:danger] = "You can only edit or delete your own posts"
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in!"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "Something went wrong with your login"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "you have successfully logged out!"
    redirect_to root_path
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def show
    @tag = Tag.find(params[:id])
    @tag_posts = @tag.posts.paginate(page: params[:page], per_page: 5)
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      flash[:notice] = "Tag successfully created!"
      redirect_to tags_path
    else
      render 'new'
    end
  end

  private
    def tag_params
        params.require(:tag).permit(:name)
    end

    def require_admin
      if !logged_in? || (logged_in? && !current_user.admin?)
        flash[:danger] = "Only admins can create a tag"
        redirect_to tags_path
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :destroy]
  before_action :redirect_unless_authorized, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "welcome to the Blog! #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def index
    @users = User.includes(:posts).all
  end

  def update

    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully!"
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @user.destroy
    flash[:danger] = "User and all articles created by user have been deleted"
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_admin
    if logged_in? && !current_user.admin?
      flash[:danger] = "Only admin users can perform that action"
      redirect_to root_path
    end
  end

  def redirect_unless_authorized
    unless current_user == @user || current_user.admin?
      flash[:danger] = "You cannot edit someone elses profile!"
      redirect_to root_path
    end
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: "profile-image")
  end
end

app/views/layouts/_navigation.html.erb
<ul>
  <li><%= link_to 'Home', root_path %></li>
  <li><%= link_to 'Posts', posts_path %></li>
  <li><%= link_to 'Users', users_path %></li>
  <% Tag.all.each do |tag| %>
    <li><%= link_to "#{tag.name}", tag_path(tag) %></li>
  <% end %>
  <% if logged_in? %>
  <%= "Admin" if current_user.admin? %>
  <li><%= link_to 'Edit Profile', edit_user_path(current_user) %></li>
  <li><%= link_to 'View Profile', user_path(current_user) %></li>
  <li><%= link_to 'Create Post', new_post_path %></li>
  <li><%= link_to 'logout', logout_path, method: :delete %></li>
  <% else %>
  <li><%= link_to 'Login', login_path %></li>
  <li><%= link_to 'sign-up', signup_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <% flash.each do |name, msg| %>
     <ul>
       <li><%= msg %></li>
     </ul>
    <% end %>
    <%= yield %>

    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>This is my home page</h1>
<p><%= link_to "Blogs", posts_path %></p>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <h2>Whoooaa there! Here's some errors</h2>
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
    <li class="errors"><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @post do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br/>
    <%= f.text_area :body %>
  </p>
    <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name do |cb| %>
      <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>
  <p>
    <%= f.submit %>
  </p>
  <%= link_to "Back", posts_path %>
<% end %>

app/views/posts/_post.html.erb
<ul class="post-list">
  <% obj.each do |post| %>
  <li class="post-preview-container">
    <h5><%= post.title %></h5>
    <p><%= truncate(post.body , length:100) %></p>
    <p> Created by:<%= post.user.username if post.user %></p>
    <p> <%= time_ago_in_words(post.created_at) %></p>
    <% if post.tags.any? %>
      <%= render post.tags %>
    <% end %>
    <% if logged_in? && (current_user == post.user || current_user.admin?) %>
      <p> <%= link_to "Edit", edit_post_path(post) %> | <%= link_to "Delete", post_path(post), method: :delete, data: {confirm: "Are you sure?"} %> </p>
    <% end %>
  </li>
  <% end %>
</ul>

app/views/posts/edit.html.erb
<h1>Edit your post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Here is all the Posts</h1>
<%= will_paginate %>
<%= render 'post', obj: @posts %>
<%= will_paginate %>

app/views/posts/new.html.erb
<h1> Create a Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1>Here is your created Post</h1>
<% if @post.user %>
  <%= gravatar_for @post.user %>
  <%= link_to @post.user.username, user_path(@post.user) %>
  <p><%= pluralize(@post.user.posts.count, "post") if @post.user.posts %></p>
<% end %>
<p>
  <%= @post.title %>
</p>
<p>
  <%= @post.body %>
</p>
<p>
  <% if @post.tags.any? %>
    <p>Tags: <%= render @post.tags %> </p>
  <% end %>

app/views/tags/_tag.html.erb
<span class="badge"><%= link_to tag.name, tag_path(tag) %> &nbsp;</span>

app/views/tags/index.html.erb
<h1> All Tags </h1>
<% @tags.each do |tag| %>
  <ul>
    <li><%= link_to tag.name, tag_path(tag) %></li>
    <li><%= pluralize(tag.posts.count, "post") %></li>
  </ul>
<% end %>

app/views/tags/new.html.erb
<% if @tag.errors.any? %>
  <h2>Whoooaa there! Here's some errors</h2>
  <ul>
    <% @tag.errors.full_messages.each do |msg| %>
    <li class="errors"><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @tag do |f| %>
  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name, placeholder: "Tag Name" %>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <%= link_to "Back", posts_path %>
<% end %>

app/views/tags/show.html.erb
<h1>Here is all <%= @tag.name %> posts</h1>
<%= will_paginate @tag_posts %>
  <%= render 'posts/post', obj: @tag_posts %>
<%= will_paginate @tag_posts %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <h2>Whoooaa there! Here's some errors</h2>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li class="errors"><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user do |f| %>
  <p>
    <%= f.label :username %><br/>
    <%= f.text_field :username, placeholder: "Username" %>
  </p>
  <p>
    <%= f.label :email %><br/>
    <%= f.email_field :email, placeholder: "email" %>
  </p>
  <p>
    <%= f.label :password %><br/>
    <%= f.password_field :password, placeholder: "password" %>
  </p>
  <p>
    <%= f.submit{@user.new_record? ? "Sign up" : "Update"} %>
  </p>
  <%= link_to "Back", posts_path %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your account</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1>All of the users</h1>

<% @users.each do |user| %>
  <%= gravatar_for user %>
  <%= link_to user.username, user_path(user) %>
  <p><%= pluralize(user.posts.length, "post") if user.posts %></p>
  <% if logged_in? && current_user.admin? %>
    <p>
      <%= link_to "Delete User", user_path(user), method: :delete,
          data: {confirm: "Are you sure you want to delete the user and all of their posts??"} %>
    </p>
  <% end %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up for the blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>Welcome to <%= @user.username %>'s page</h1>


<%= gravatar_for @user %>

<h4> <%= @user.username %>'s articles </h4>

<%= render 'posts/post', obj: @user.posts %>